# third_party/xprof/convert/test_xplanes/BUILD

package(default_visibility = ["@org_xprof//xprof/convert:__subpackages__"])

exports_files([
    "tpu_inference_2.xplane.pb",
    "gpu_training_2.xplane.pb",
])
