import {HttpClient, HttpParams} from '@angular/common/http';
import {inject, Injectable} from '@angular/core';
import {firstValueFrom, ReplaySubject} from 'rxjs';

import {Address, Content, SourceCodeServiceInterface} from './source_code_service_interface';
import {SyntaxHighlightService} from './syntax_highlight_service';

interface SourceCodeResponse {
  changeList: number;
  fileContent: string;
}

/**
 * A service for loading source code from Google 3.
 *
 * This service is responsible for loading source code around a stack frame.
 * It uses a cache to (temporarily) store loaded contents. UI uses this
 * interface many times to load source code around different stack frames.
 */
@Injectable()
export class SourceCodeService implements SourceCodeServiceInterface {
  private readonly cache = new Map<string, Promise<readonly string[]>>();
  private readonly syntaxHighlighter: SyntaxHighlightService =
      inject(SyntaxHighlightService);
  private readonly http: HttpClient = inject(HttpClient);
  private readonly API_BASE_URL = '/source_code';
  private readonly changeListSubject = new ReplaySubject<number>(1);
  private changeList: number|undefined = undefined;

  async loadContent(sessionId: string, addr: Address): Promise<Content> {
    const fileName = addr.fileName;
    let lines = this.cache.get(fileName);
    if (!lines) {
      lines = this.fetchFile(sessionId, addr);
      this.cache.set(fileName, lines);
    }
    return buildContent(await lines, addr);
  }

  async codeSearchLink(sessionId: string, fileName: string, lineNumber: number):
      Promise<string> {
    const changeList = await firstValueFrom(this.changeListSubject);
    return codeSearchLink(sessionId, fileName, lineNumber, changeList);
  }

  /**
   * Fetches the file content from the server. If the file content is already
   * cached, it is returned. Otherwise, the file content is fetched from the
   * server, its syntax is highlighted, its HTML tags are localized, and the
   * result is cached. Any HTML tags that are opened on a line, is also closed
   * on the same line. This is useful for scenarios where individual lines of
   * highlighted code might be processed or displayed separately, preventing
   * broken HTML structures.
   *
   * @param sessionId XProf session ID.
   * @param addr An address of the source code.
   * @return The content of the source code.
   */
  private async fetchFile(sessionId: string, addr: Address):
      Promise<readonly string[]> {
    const fileName = addr.fileName;
    const params = new HttpParams()
                       .set('session_id', sessionId)
                       .set('change_list', this.changeList || 0)
                       .set('file_path', `//depot/google3/${fileName}`);
    const response = await firstValueFrom(
        this.http.get<SourceCodeResponse>(this.API_BASE_URL, {params}));
    if (!response.fileContent || response.changeList === undefined) {
      throw new Error(`Response does not contain the expected fields.`);
    }
    this.changeList = response.changeList;
    this.changeListSubject.next(response.changeList);
    const content = response.fileContent;
    const highlighted = this.syntaxHighlighter.highlight(content, fileName);
    const localized = ensureTagsClosedPerLine(highlighted.value);
    console.log('Cached file: ', fileName);
    return localized;
  }
}

/**
 * Builds a content from the input `lines` and the `address`.
 *
 * @param lines The lines of the source code file.
 * @param addr An address of the source code snippet.
 * @return The content of the source code snippet. If the content cannot be
 *     built, it returns a `Failure`.
 */
function buildContent(lines: readonly string[], addr: Address): Content {
  const lineIndex = addr.lineNumber - 1;
  const startIndex = Math.max(0, lineIndex - addr.linesBefore);
  const endIndex = Math.min(lines.length, addr.lineNumber + addr.linesAfter);
  if (lineIndex < startIndex || lineIndex >= endIndex) {
    throw new Error(`The requested line number ${
        addr.lineNumber} is not found in the file.`);
  }
  return new Content(addr, startIndex + 1, lines.slice(startIndex, endIndex));
}

/**
 * Processes a highlighted HTML string to ensure that all HTML tags opened on a
 * line are also closed on the same line. If a tag spans multiple lines in the
 * input, it will be closed at the end of the line it starts on and reopened at
 * the start of the subsequent lines it continues onto. Furthermore, all new
 * lines that occur inside a HTML tag attribute will be escaped.
 *
 * This is useful for scenarios where individual lines of highlighted code might
 * be processed or displayed separately, preventing broken HTML structures.
 *
 * @param html A HTML string generated by a syntax highlighter like
 *   `highlight.js`.
 * @return A new HTML string split into multiple lines. Each line represents
 *     one line of the source code and any tags that were opened on a line are
 *     also closed on the same line.
 */
function ensureTagsClosedPerLine(html: string): string[] {
  const lines: string[] = [];
  const openTags: string[] = [];
  const closeTags: string[] = [];

  // Regex to break a multi-line string into tokens:
  // 1. Matches a complete HTML tag (e.g., <span class="foo">, </span>, <br />).
  //    It also supports unescaped `<` and `>` in attribute values.
  // 2. Matches anything else (text content).
  // Since we cannot use `s` flag, prefer not to use `.` in the following regex.
  // Otherwise, the following error is generated:
  // > ERROR - [JSC_UNTRANSPILABLE] Cannot convert feature "RegExp flag 's'" to
  // > targeted output language. Feature requires at minimum ECMASCRIPT_2018.
  // > Consider targeting a more modern output.
  const tokenPattern =
      /(<\/?\s*([_.a-zA-Z][-_.a-zA-Z0-9]*)(?:[^>'"]|(?:'(?:[^']|\\')*')|(?:"(?:[^"]|\\")*"))*\/?>)|([^<]+)/g;

  let currentLine = '';
  let match: RegExpExecArray|null;
  while ((match = tokenPattern.exec(html)) !== null) {
    if (match[1]) {
      // This is a tag. Escape new lines.
      const tag = match[1].replace(/(\r\n|\r|\n)/g, '&#10;');
      currentLine += tag;
      if (tag.startsWith('</')) {
        openTags.pop();
        closeTags.pop();
      } else {
        if (!tag.endsWith('/>')) {
          // This is an opening tag. Create a closing tag.
          const closeTag = match[2].replace(/(\r\n|\r|\n)/g, '&#10;');
          openTags.push(tag);
          closeTags.push(`</${closeTag}>`);
        }
      }
    }
    if (match[3]) {
      // This is a text content. Separate the lines.
      const content = match[3];
      const subLines = content.split('\n');
      currentLine += subLines[0];
      if (subLines.length > 1) {
        const opening = openTags.join('');
        const closing = closeTags.reverse().join('');
        for (const subLine of subLines.slice(1)) {
          lines.push(currentLine + closing);
          currentLine = opening + subLine;
        }
      }
    }
  }

  return lines;
}

function codeSearchLink(
    sessionId: string, fileName: string, lineNumber: number,
    changeList: number): string {
  const prefix = `https://source.corp.google.com/piper///depot/google3/${
      fileName};l=${lineNumber}`;
  return (changeList === 0) ? prefix : `${prefix};rcl=${changeList}`;
}
