#include "frontend/app/components/trace_viewer_v2/color/color_generator.h"

#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#endif

#include <cmath>
#include <cstddef>
#include <vector>

#include "absl/base/no_destructor.h"
#include "absl/container/flat_hash_map.h"
#include "absl/hash/hash.h"
#include "absl/strings/string_view.h"
#include "imgui.h"
#include "frontend/app/components/trace_viewer_v2/color/colors.h"

namespace traceviewer {

namespace {

static constexpr ImU32 event_colors[] = {
    kPurple70,
    kGreen80,
    kBlue80,
    kYellow90,
};

// Generates colors based on string IDs.
// The color is generated by hashing the ID and picking a color from a
// predefined list.
class ColorGenerator {
 public:
  ColorGenerator(const ColorGenerator&) = delete;
  ColorGenerator& operator=(const ColorGenerator&) = delete;
  ColorGenerator(ColorGenerator&&) = delete;
  ColorGenerator& operator=(ColorGenerator&&) = delete;

  // Returns a color for the given ID.
  ImU32 ColorForId(absl::string_view id) {
    return event_colors[absl::Hash<absl::string_view>{}(id) %
                        std::size(event_colors)];
  }

 private:
  friend class absl::NoDestructor<ColorGenerator>;
  ColorGenerator() = default;
};

}  // namespace

// Generates a color for a given string ID.
// The color is generated by hashing the ID and picking a color from a
// predefined list.
ImU32 GetColorForId(absl::string_view id) {
  static absl::NoDestructor<ColorGenerator> generator;
  return generator->ColorForId(id);
}

}  // namespace traceviewer
