# Copyright 2019 The TensorFlow Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""Discover tools available for a profile run."""

from __future__ import annotations

import os
from collections.abc import Sequence

from xprof.profile_plugin.logging_config import logger
from xprof.profile_plugin.tools.filenames import parse_filename
from xprof.profile_plugin.tools.registry import XPLANE_TOOLS, sort_tools


def get_tools_from_filenames(
    filenames: Sequence[str], profile_run_dir: str
) -> set[str]:
  """Parses a sequence of filenames and returns the set of tools.

  If xplane is present in the repository, add tools that can be generated by
  xplane if we don't have a file for the tool.

  Args:
    filenames: A sequence of filenames.
    profile_run_dir: The run directory of the profile.

  Returns:
    A set of tool names encoded in the filenames.
  """
  tools = set()
  found = set()
  xplane_filenames = []
  for name in filenames:
    _, tool = parse_filename(name)
    if tool == 'xplane':
      xplane_filenames.append(os.path.join(profile_run_dir, name))
      continue
    elif tool == 'hlo_proto':
      continue
    elif tool:
      tools.add(tool)
      if tool[-1] in ('@'):
        found.add(tool[:-1])
      else:
        found.add(tool)
  # profile_run_dir might be empty, like in cloud AI use case.
  if not profile_run_dir:
    if xplane_filenames:
      for item in XPLANE_TOOLS:
        if item[:-1] not in found:
          tools.add(item)
  else:
    try:
      if xplane_filenames:
        from xprof.convert import raw_to_tool_data as convert  # pylint: disable=g-import-not-at-top
        return set(convert.xspace_to_tool_names(xplane_filenames))
    except AttributeError:
      logger.warning('XPlane converters are available after Tensorflow 2.4')
  return tools


def get_active_tools(filenames: Sequence[str], profile_run_dir: str = '') -> list[str]:
  """Get a list of tools available given the filenames created by profiler.

  Args:
    filenames: List of strings that represent filenames
    profile_run_dir: The run directory of the profile.

  Returns:
    A list of strings representing the available tools
  """
  tools = get_tools_from_filenames(filenames, profile_run_dir)
  if 'trace_viewer@' in tools:
    # streaming trace viewer always override normal trace viewer.
    # the trailing '@' is to inform tf-profile-dashboard.html and
    # tf-trace-viewer.html that stream trace viewer should be used.
    tools.discard('trace_viewer')

  return sort_tools(tools)
