#ifndef THIRD_PARTY_XPROF_UTILS_TPU_COUNTER_IDS_V7_H_
#define THIRD_PARTY_XPROF_UTILS_TPU_COUNTER_IDS_V7_H_

#include <cstdint>

namespace xprof {

// Enum of TPU counter IDs.
enum TpuCounterIdsTpu7 : uint64_t {
  // NOLINTBEGIN
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_CYCLES =
      3257466888,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_BF16_MXU_0 =
      3257467352,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_BF16_MXU_1 =
      3257467360,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_I4_MXU_0 =
      3257467384,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_I4_MXU_1 =
      3257467392,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_I8_MXU_0 =
      3257467368,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_LMR_I8_MXU_1 =
      3257467376,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_BF16_MXU_0 =
      3257467288,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_BF16_MXU_1 =
      3257467296,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F32_MXU_0 =
      3257467272,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F32_MXU_1 =
      3257467280,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F8_MXU_0 =
      3257467304,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_F8_MXU_1 =
      3257467312,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_I4_MXU_0 =
      3257467336,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_I4_MXU_1 =
      3257467344,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_I8_MXU_0 =
      3257467320,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATMUL_VREG_I8_MXU_1 =
      3257467328,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATPUSH_CYCLES_MXU_0 =
      3257467440,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MATPUSH_CYCLES_MXU_1 =
      3257467448,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_0 =
      3257467400,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_1 =
      3257467408,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_MXU_BUSY_2 =
      3257467416,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_PACKED_XLU_0 =
      3257467520,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_PACKED_XLU_1 =
      3257467528,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_INSTRUCTION_XLU_0 =
      3257467472,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_INSTRUCTION_XLU_1 =
      3257467480,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_SET_INSTRUCTION_XLU_0 =
      3257467488,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_ROTATE_PERMUTE_SET_INSTRUCTION_XLU_1 =
      3257467496,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_SCALAR_ALU_INSTRUCTION_0 =
      3257466968,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_SCALAR_ALU_INSTRUCTION_1 =
      3257466976,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_TRANSPOSE_XLU_0 =
      3257467504,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_TRANSPOSE_XLU_1 =
      3257467512,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_0 =
      3257467136,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_1 =
      3257467144,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_2 =
      3257467152,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VECTOR_ALU_INSTRUCTION_3 =
      3257467160,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VLD_INSTRUCTION_0 =
      3257467184,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VLD_INSTRUCTION_1 =
      3257467192,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_VST_INSTRUCTION =
      3257467168,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_0 =
      3257467536,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_1 =
      3257467544,
  VF_CHIP_TC_TCS_TC_MISC_TCS_STATS_TCS_STATS_COUNTERS_UNPRIVILEGED_COUNT_XLU_BUSY_2 =
      3257467552,
  // NOLINTEND
};

}  // namespace xprof

#endif  // THIRD_PARTY_XPROF_UTILS_TPU_COUNTER_IDS_V7_H_
