load("//defs:defs.bzl", ts_library = "xprof_ng_module")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "memory_usage",
    srcs = [
        "memory_usage.ts",
    ],
    deps = [
        "@org_xprof//frontend/app/common/interfaces",
        "@org_xprof//frontend/app/common/utils",
    ],
)
