# Description:
#   Component Rack Material 3 design tokens for XProf.
load("//defs:defs.bzl", "sass_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

sass_library(
    name = "rack_theme",
    srcs = [
        "_colors_dark.scss",
        "_colors_light.scss",
        "_elevation.scss",
        "_icons.scss",
        "_index.scss",
        "_motion.scss",
        "_shape.scss",
        "_spacing.scss",
        "_typography.scss",
    ],
)
