load("//defs:defs.bzl", ts_library = "xprof_ng_module")

package(default_visibility = ["@org_xprof//frontend:__subpackages__"])

ts_library(
    name = "classes",
    srcs = [
        "throbber.ts",
    ],
    deps = [
        "@org_xprof//frontend/app/common/interfaces",
    ],
)
