load("@npm//@bazel/concatjs:index.bzl", "ts_library")

package(default_visibility = ["//frontend:internal"])

ts_library(
    name = "data",
    srcs = [
        "data_component_keywords.ts",
        "data_sampling_info.ts",
        "data_tpu_generations.ts",
    ],
)
