load("//defs:defs.bzl", "xprof_ng_module")

package(default_visibility = ["//frontend:internal"])

xprof_ng_module(
    name = "angular_common_http",
    srcs = [],
    deps = [
        "//:node_modules/@angular/common",
    ],
)

xprof_ng_module(
    name = "angular_platform-browser_animation",
    srcs = [],
    deps = [
        "//:node_modules/@angular/platform-browser",
    ],
)

xprof_ng_module(
    name = "angular_material_expansion",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_progress_bar",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_form_field",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_icon",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_input",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_button",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_divider",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_menu",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_sidenav",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_checkbox",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_dialog",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_radio",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_progress_spinner",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_snack_bar",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_card",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_slide_toggle",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_slider",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_tooltip",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_core",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_select",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_list",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)

xprof_ng_module(
    name = "angular_material_toolbar",
    srcs = [],
    deps = [
        "//:node_modules/@angular/material",
    ],
)
